// TODO: Delete this after testing
export default {
	id: 108,
	email: 'user2@onplan.tech',
	abbreviatedName: 'UT',
	displayName: 'User2 Test',
	companyName: 'UAT TECKTEST',
	settings: [
		{
			id: 1,
			name: 'Mobile job operation',
			description: 'Colour for mobile job operation card',
			value: '#448AFF',
			className: 'mobile-jo-card',
			isVisible: 1,
			createdAt: '2020-01-20 15:58:21',
			createdBy: null,
			updatedAt: '2019-09-30 19:06:34',
			updatedBy: null
		},
		{
			id: 2,
			name: 'Fixed Plant job operation',
			description: 'Colour for fixed plant job operation card',
			value: '#448AFF',
			className: 'fixedplant-jo-card',
			isVisible: 1,
			createdAt: '2020-01-20 15:58:21',
			createdBy: null,
			updatedAt: '2019-09-30 19:06:34',
			updatedBy: null
		},
		{
			id: 3,
			name: 'Global Mobile job operation',
			description: 'Colour for global mobile job operation card',
			value: '#4CAF52',
			className: 'global-mobile-jo-card',
			isVisible: 1,
			createdAt: '2020-01-20 15:58:21',
			createdBy: null,
			updatedAt: '2019-09-30 19:06:34',
			updatedBy: null
		},
		{
			id: 4,
			name: 'Global Fixed Plant job operation',
			description: 'Colour for global fixed plant job operation card',
			value: '#E09400',
			className: 'global-fixedplant-jo-card',
			isVisible: 1,
			createdAt: '2020-01-20 15:58:21',
			createdBy: null,
			updatedAt: '2020-05-03 08:42:13',
			updatedBy: 4
		},
		{
			id: 5,
			name: 'Both Mobile and Fixed Plant job operation',
			description: 'Colour for both mobile and fixed plant job operation card',
			value: '#448AFF',
			className: 'both-jo-card',
			isVisible: 1,
			createdAt: '2020-01-20 15:58:21',
			createdBy: null,
			updatedAt: '2019-09-30 19:06:34',
			updatedBy: null
		},
		{
			id: 6,
			name: 'Global both Mobile and Fixed Plant job operation',
			description: 'Colour for global both mobile and fixed plant job operation card',
			value: '#4CAF52',
			className: 'global-both-jo-card',
			isVisible: 1,
			createdAt: '2020-01-20 15:58:21',
			createdBy: null,
			updatedAt: '2019-09-30 19:06:34',
			updatedBy: null
		},
		{
			id: 8,
			name: 'Editor Toolbar',
			description: 'Enable / Disable step instruction editor toolbar',
			value: '1',
			className: 'quilljs',
			isVisible: 1,
			createdAt: '2020-01-20 15:58:21',
			createdBy: null,
			updatedAt: '2020-03-12 09:00:30',
			updatedBy: 4
		},
		{
			id: 9,
			name: 'Use Client Side Menu',
			description: 'Advantage side menu configured for clients.',
			value: '0',
			className: 'sideMenu',
			isVisible: 0,
			createdAt: '2020-01-20 15:58:21',
			createdBy: null,
			updatedAt: '2020-01-31 15:50:13',
			updatedBy: null
		},
		{
			id: 10,
			name: 'Not Started',
			description: 'Status label and colour for "Not Started" work instructions',
			value: '#F44336',
			className: 'status-NotStarted',
			isVisible: 1,
			createdAt: '2020-01-20 15:58:21',
			createdBy: null,
			updatedAt: '2019-10-28 14:45:15',
			updatedBy: null
		},
		{
			id: 11,
			name: 'In Progress',
			description: 'Status label and colour for "In Progress" work instructions',
			value: '#FFB300',
			className: 'status-InProgress',
			isVisible: 1,
			createdAt: '2020-01-20 15:58:21',
			createdBy: null,
			updatedAt: '2019-10-24 11:32:58',
			updatedBy: null
		},
		{
			id: 12,
			name: 'Draft Complete',
			description: 'Status label and colour for "Draft Complete" work instructions',
			value: '#777777',
			className: 'status-DraftComplete',
			isVisible: 1,
			createdAt: '2020-01-20 15:58:21',
			createdBy: null,
			updatedAt: '2019-10-28 13:45:45',
			updatedBy: null
		},
		{
			id: 13,
			name: 'Level 1 Review',
			description: 'Status label and colour for "Level 1 Review" work instructions',
			value: '#448AFF',
			className: 'status-Level1Review',
			isVisible: 1,
			createdAt: '2020-01-20 15:58:21',
			createdBy: null,
			updatedAt: '2019-10-28 14:46:03',
			updatedBy: null
		},
		{
			id: 14,
			name: 'Level 2 Review',
			description: 'Status label and colour for "Level 2 Review" work instructions',
			value: '#448AFF',
			className: 'status-Level2Review',
			isVisible: 1,
			createdAt: '2020-01-20 15:58:21',
			createdBy: null,
			updatedAt: '2019-10-24 11:32:58',
			updatedBy: null
		},
		{
			id: 15,
			name: 'Approved',
			description: 'Status label and colour for "Approved" work instructions',
			value: '#4CAF50',
			className: 'status-Approved',
			isVisible: 1,
			createdAt: '2020-01-20 15:58:21',
			createdBy: null,
			updatedAt: '2019-10-28 14:52:07',
			updatedBy: null
		},
		{
			id: 16,
			name: "Default 'Show Templates' Toggle",
			description: "Toggle 'Show Templates' switch",
			value: '0',
			className: 'defaultShowTemplate',
			isVisible: 1,
			createdAt: '2020-01-20 15:58:21',
			createdBy: null,
			updatedAt: '2021-05-17 16:50:33',
			updatedBy: 26
		},
		{
			id: 17,
			name: 'Task Editing',
			description: 'Enable Task editing from within Asset Navigation',
			value: '1',
			className: 'customerStratEditing',
			isVisible: 1,
			createdAt: '2020-01-20 15:58:21',
			createdBy: null,
			updatedAt: '2020-03-12 09:01:09',
			updatedBy: 4
		},
		{
			id: 18,
			name: 'Enable Dynamic Hazard Creation',
			description: 'Enable hazard advice creation from the advice menu on work instructions',
			value: '1',
			className: 'dynamicAddHazard',
			isVisible: 1,
			createdAt: '2020-01-31 15:50:13',
			createdBy: null,
			updatedAt: '2022-02-03 06:50:20',
			updatedBy: 26
		},
		{
			id: 19,
			name: 'Allow Work Order management in KrackOn',
			description: 'Toggle Work Order creation within KrackOn',
			value: '1',
			className: 'workOrderCreation',
			isVisible: 1,
			createdAt: '2020-01-31 15:50:13',
			createdBy: null,
			updatedAt: '2021-05-14 07:14:29',
			updatedBy: 26
		},
		{
			id: 20,
			name: 'Restrict Work Orders to only Structural Inspection',
			description: 'Allow only Structual Inspection Strategy Tasks for Work Order creation',
			value: '',
			className: 'restrictWorkOrderType',
			isVisible: 0,
			createdAt: '2020-02-21 15:26:01',
			createdBy: null,
			updatedAt: '2021-05-14 07:13:55',
			updatedBy: 26
		},
		{
			id: 21,
			name: 'Make allocating Owners to Strategy Tasks mandatory',
			description:
				'This will make the Owners field on all Strategy Task creation screens mandatory',
			value: '1',
			className: 'mandatoryOwnersForStrategyTasks',
			isVisible: 1,
			createdAt: '2020-04-24 07:25:01',
			createdBy: null,
			updatedAt: '2021-09-15 11:35:05',
			updatedBy: 26
		},
		{
			id: 22,
			name: 'Enforce Single Login',
			description: 'Allow only one login per user.',
			value: '1',
			className: 'singleLogin',
			isVisible: 0,
			createdAt: '2020-06-05 18:59:07',
			createdBy: null,
			updatedAt: '2020-06-05 18:59:07',
			updatedBy: null
		},
		{
			id: 23,
			name: 'Combine Small Steps',
			description: 'Combine small steps into one big step on work orders',
			value: '1',
			className: 'workOrderCombinedSteps',
			isVisible: 1,
			createdAt: '2020-07-24 19:53:24',
			createdBy: null,
			updatedAt: '2023-05-18 11:59:02',
			updatedBy: 108
		},
		{
			id: 24,
			name: 'Show PM Builder',
			description: 'PM Builder related functions will be enabled.',
			value: '1',
			className: 'showPMBuilder',
			isVisible: 0,
			createdAt: '2020-07-24 19:53:24',
			createdBy: null,
			updatedAt: '2021-05-14 07:13:36',
			updatedBy: 26
		},
		{
			id: 25,
			name: "Default 'Show FMECA Columns' Toggle",
			description: "Toggle 'Show FMECA Columns' switch",
			value: '1',
			className: 'defaultShowFmeca',
			isVisible: 1,
			createdAt: '2021-03-03 17:27:30',
			createdBy: null,
			updatedAt: '2021-05-14 07:14:09',
			updatedBy: 26
		},
		{
			id: 26,
			name: 'Grafana Organization Id',
			description: 'Used to identify what Grafana organization maps to this database',
			value: '49',
			className: 'grafanaId',
			isVisible: 0,
			createdAt: '2021-05-24 18:47:18',
			createdBy: null,
			updatedAt: '2022-02-28 10:06:21',
			updatedBy: null
		},
		{
			id: 27,
			name: 'Maintenance Mode',
			description: 'Enable / Disable maintenance mode for this database',
			value: '0',
			className: 'maintenanceMode',
			isVisible: 0,
			createdAt: '2021-06-18 21:33:54',
			createdBy: null,
			updatedAt: '2021-06-18 21:33:54',
			updatedBy: null
		},
		{
			id: 28,
			name: 'Auto-assign App Users to a Work Order',
			description: 'Toggle current User being auto assigned to the Work Order edited',
			value: '0',
			className: 'workOrderUserAssign',
			isVisible: 1,
			createdAt: '2021-07-30 20:05:06',
			createdBy: null,
			updatedAt: '2021-07-30 20:05:06',
			updatedBy: null
		},
		{
			id: 29,
			name: 'Work Order must have a user assigned to start',
			description: 'Toggle Work Orders requiring assigned Users before starting',
			value: '0',
			className: 'workOrderUserRequired',
			isVisible: 1,
			createdAt: '2021-07-30 20:05:06',
			createdBy: null,
			updatedAt: '2021-07-30 20:05:06',
			updatedBy: null
		},
		{
			id: 30,
			name: 'Builder Only Mode',
			description: 'Hide Job Management, Reporting and App User menu items',
			value: '0',
			className: 'builderOnlyMode',
			isVisible: 0,
			createdAt: '2022-02-18 20:10:49',
			createdBy: null,
			updatedAt: '2022-02-18 20:10:49',
			updatedBy: null
		},
		{
			id: 31,
			name: 'OnPlan app - Save to Cloud',
			description:
				'Enable to stop automatic saving of work order data to the cloud (useful with unreliable internet).',
			value: '1',
			className: 'saveToCloud',
			isVisible: 1,
			createdAt: '2022-02-18 20:10:50',
			createdBy: null,
			updatedAt: '2023-06-07 09:14:29',
			updatedBy: 108
		},
		{
			id: 32,
			name: 'Enable Work Order Annotation Mode',
			description:
				'Finished work orders are set to "Awaiting Finalisation", requiring review/adding of optional notes to the work order and then "Finalise" the work order. Typically for report delivery to a customer. Overrides any site-level Work Order Approval workflow.',
			value: '0',
			className: 'enableWorkOrderAnnotationMode',
			isVisible: 1,
			createdAt: '2022-05-07 08:37:47',
			createdBy: null,
			updatedAt: '2022-05-07 08:37:47',
			updatedBy: null
		},
		{
			id: 33,
			name: 'Autofill WorkOrder Description with Component Code',
			description:
				'While creating a work order, its description is auto-filled with Task Name. If enabled, the description is auto-filled with Component Code instead',
			value: '0',
			className: 'enableAutoFillWithTaskCode',
			isVisible: 1,
			createdAt: '2022-06-18 08:58:15',
			createdBy: null,
			updatedAt: '2022-06-18 08:58:15',
			updatedBy: null
		},
		{
			id: 34,
			name: 'Service Company Mode',
			description:
				'Provides an OnPlan experience designed to help service companies perform tasks more efficiently.',
			value: '0',
			className: 'serviceCompanyWorkOrder',
			isVisible: 1,
			createdAt: '2021-05-24 18:34:13',
			createdBy: null,
			updatedAt: '2022-08-20 10:07:27',
			updatedBy: null
		},
		{
			id: 35,
			name: 'Supervisor Dashboard Date Filter Range',
			description:
				'Set how many days on either side of the current date to show work orders on the supervisor dashboard.',
			value: '7',
			className: 'supervisorDateFilterRange',
			isVisible: 1,
			createdAt: '2021-05-24 18:34:13',
			createdBy: null,
			updatedAt: '2022-06-18 08:58:15',
			updatedBy: 31
		},
		{
			id: 36,
			name: 'Deselect App "Create Defect" checkboxes by default',
			description:
				'When completing a Work Order, the "Create Defect" checkboxes for incomplete steps will default to unselected.',
			value: '0',
			className: 'deselectAppCreateDefectCheckBoxes',
			isVisible: 1,
			createdAt: '2022-06-18 08:58:15',
			createdBy: null,
			updatedAt: '2022-06-18 08:58:15',
			updatedBy: null
		},
		{
			id: 37,
			name: 'Toggle Work Order Completion Report Public Links',
			description: 'Allow public access to work order completion report PDF link',
			value: '1',
			className: 'workOrderCompletionReport',
			isVisible: 1,
			createdAt: '2022-06-18 08:58:15',
			createdBy: null,
			updatedAt: '2022-06-18 08:58:15',
			updatedBy: null
		},
		{
			id: 38,
			name: 'Defect Integration',
			description: 'Activate Work Order Defect (sub level) Third Party API Integration',
			value: '1',
			className: 'defectIntegration',
			isVisible: 0,
			createdAt: '2022-08-20 10:07:14',
			createdBy: null,
			updatedAt: '2023-05-12 09:59:04',
			updatedBy: 26
		},
		{
			id: 39,
			name: 'Work Order Integration',
			description: 'Activate Work Order Third Party API Integration',
			value: '1',
			className: 'workOrderIntegration',
			isVisible: 0,
			createdAt: '2022-07-15 16:11:45',
			createdBy: null,
			updatedAt: '2023-05-26 11:22:06',
			updatedBy: 26
		},
		{
			id: 40,
			name: 'Top nav bar background colour',
			description: "This controls the styling of Builder's navigation bar",
			value: '',
			className: 'displaySetting-topNavBarBgColour',
			isVisible: 0,
			createdAt: '2022-08-20 10:07:20',
			createdBy: null,
			updatedAt: '2022-08-20 10:07:20',
			updatedBy: null
		},
		{
			id: 41,
			name: 'Side menu background colour',
			description: "This controls the background colour of Builder's side menu",
			value: '',
			className: 'displaySetting-sideMenuBgColour',
			isVisible: 0,
			createdAt: '2022-08-20 10:07:20',
			createdBy: null,
			updatedAt: '2022-08-20 10:07:20',
			updatedBy: null
		},
		{
			id: 42,
			name: 'Side menu icon colour',
			description: "This controls the styling of Builder's side menu icon colours",
			value: '',
			className: 'displaySetting-sideMenuIconsColour',
			isVisible: 0,
			createdAt: '2022-08-20 10:07:20',
			createdBy: null,
			updatedAt: '2022-08-20 10:07:20',
			updatedBy: null
		},
		{
			id: 43,
			name: 'Top nav bar icon colour',
			description: "This controls Builder's top nav bar icon colour",
			value: '',
			className: 'displaySetting-topNavBarIconsColour',
			isVisible: 0,
			createdAt: '2022-08-20 10:07:20',
			createdBy: null,
			updatedAt: '2022-08-20 10:07:20',
			updatedBy: null
		},
		{
			id: 44,
			name: 'Foreground colour',
			description: "This controls Builder's general foreground colour",
			value: '',
			className: 'displaySetting-foregroundColour',
			isVisible: 0,
			createdAt: '2022-08-20 10:07:20',
			createdBy: null,
			updatedAt: '2022-08-20 10:07:20',
			updatedBy: null
		},
		{
			id: 45,
			name: 'General font colour',
			description: "This controls Builder's general font colour",
			value: '',
			className: 'displaySetting-generalFontColour',
			isVisible: 0,
			createdAt: '2022-08-20 10:07:20',
			createdBy: null,
			updatedAt: '2022-08-20 10:07:20',
			updatedBy: null
		},
		{
			id: 46,
			name: 'Side menu Font colour',
			description: "This controls Builder's side menu",
			value: '',
			className: 'displaySetting-sideMenuFontcolour',
			isVisible: 0,
			createdAt: '2022-08-20 10:07:20',
			createdBy: null,
			updatedAt: '2022-08-20 10:07:20',
			updatedBy: null
		},
		{
			id: 47,
			name: 'Company Logo',
			description: 'Upload a custom Builder logo',
			value: '/img/onplan.png',
			className: 'displaySetting-companyLogo',
			isVisible: 0,
			createdAt: '2022-08-20 10:07:20',
			createdBy: null,
			updatedAt: '2022-08-20 10:07:20',
			updatedBy: null
		},
		{
			id: 48,
			name: 'Enable OnPlan App Tardigrade Mode by default',
			description:
				'OnPlan App will default to a slower, but more reliable work order save-to-cloud approach - for choppy / unreliable site Internet.',
			value: '1',
			className: 'tardigradeMode',
			isVisible: 0,
			createdAt: '2022-08-20 10:07:21',
			createdBy: null,
			updatedAt: '2022-08-20 10:11:17',
			updatedBy: 26
		},
		{
			id: 49,
			name: 'WIN Document Status Change Request',
			description:
				'If enabled, when user clicks Do Not Send Request button, WIN status stays the same',
			value: '0',
			className: 'WINStatus',
			isVisible: 1,
			createdAt: '2023-01-24 23:13:23',
			createdBy: null,
			updatedAt: '2023-01-24 23:13:23',
			updatedBy: null
		},
		{
			id: 51,
			name: 'Pre-populate OnPlan App New Defect',
			description: 'Uses step information to pre-populate some defect fields in OnPlan App.',
			value: '1',
			className: 'appPrepopulateNewDefects',
			isVisible: 1,
			createdAt: '2023-04-27 10:47:35',
			createdBy: null,
			updatedAt: '2023-04-27 10:47:35',
			updatedBy: null
		},
		{
			id: 52,
			name: 'Step Autocomplete',
			description:
				'Mark step done automatically if all step conditions are completed. Moving to the next step automatically is also disabled',
			value: '0',
			className: 'stepAutoComplete',
			isVisible: 1,
			createdAt: '2023-05-09 12:46:30',
			createdBy: null,
			updatedAt: '2023-05-18 14:31:26',
			updatedBy: 108
		},
		{
			id: 53,
			name: 'Disable GPS',
			description: "If enabled, browser won't ask for GPS location",
			value: '0',
			className: 'disableGPS',
			isVisible: 1,
			createdAt: '2023-05-09 12:46:30',
			createdBy: null,
			updatedAt: '2023-05-09 12:46:30',
			updatedBy: null
		},
		{
			id: 54,
			name: 'Automatic Author Details & Operations Lock',
			description:
				'If enabled, "Author" field is prefilled with the logged in user details. Also, it automatically locks all operations within the WIN Document when the status of the document changes to "Approved"',
			value: '0',
			className: 'autoAuthorDetlsOpLock',
			isVisible: 1,
			createdAt: '2023-05-09 12:46:30',
			createdBy: null,
			updatedAt: '2023-05-09 12:46:30',
			updatedBy: null
		},
		{
			id: 55,
			name: 'Only report for Complete Work Orders',
			description:
				'Always show report for Complete Work Orders instead of change status to inclomplete popup',
			value: '0',
			className: 'reportOnlyForCompleteWO',
			isVisible: 0,
			createdAt: '2023-05-09 12:46:30',
			createdBy: null,
			updatedAt: '2023-05-09 12:46:30',
			updatedBy: null
		},
		{
			id: 56,
			name: 'OnPlan App - Camera only',
			description: "Disables attaching existing photos via a device's image gallery.",
			value: '0',
			className: 'appCameraOnly',
			isVisible: 1,
			createdAt: '2023-06-21 12:15:29',
			createdBy: null,
			updatedAt: '2023-06-21 12:15:29',
			updatedBy: null
		},
		{
			id: 57,
			name: 'OnPlan App - pre-cache all Work Order data',
			description: 'Pre-cache all Work Order data on app-load for maximum offline support.',
			value: '0',
			className: 'preDownloadAppWorkOrderData',
			isVisible: 1,
			createdAt: '2023-06-21 12:15:30',
			createdBy: null,
			updatedAt: '2023-06-21 12:15:30',
			updatedBy: null
		}
	],
	dictionaryDefinitions: {
		'Functional Location': 'Unit Number',
		'SAP Document Number': 'Document Number',
		Customer: 'Site',
		'Equipment Grouping / Model': 'Model',
		'Reference / Manufacturer': 'Manufacturer',
		'Equipment Grouping / Models': 'Models',
		'Manufacturer / Reference': 'Manufacturer',
		'#crackLengthLabelLength (mm) *': 'Length (inch) *',
		'.lengthUnitsmm': 'Inch',
		'#sidebar__feedbackFeedback': 'Green Pen List',
		'#defectTitleProvide Feedback': 'Add Green Pen Comment',
		'Length (mm)': 'Length (inch)',
		'Open Preview and Red Pen Editor': 'Open Preview and Green Pen Editor',
		'.viewer-titleTask WIN Preview And Red Pen Editor': 'Task WIN Preview And Green Pen Editor',
		'.helloGrowth (mm/day)': 'Growth (inch/day)',
		'.growthUnitsmm / day': 'inch / day',
		'Add Defect': 'Found Work',
		'Add New Defect': 'Add Found Work',
		'Crack Length (mm)': 'Crack Length (inch)',
		'Create Defect': 'New Found Work',
		Defect: 'Found Work',
		'Defect Number': 'Found Work Number',
		Defects: 'Found Work',
		'Delete Feedback': 'Delete Green Pen',
		'Edit Defects': 'Edit Found Work',
		'Edit Feedback': 'Edit Green Pen',
		'.recordResultButton btn btn-default btn-primary actionButtons d-none d-md-none d-lg-inline-blockFeedback':
			'Green Pen',
		'.mt-10 mb-4 truncateFeedback': 'Green Pen',
		'Growth Profile (mm)': 'Growth Profile (inch)',
		'.strongMeasurement Units = mm': 'Measurement Units = inch',
		'.strongMeasurment Units = mm': 'Measurement Units = inch',
		'.crackMeasurementUnitmm': 'inch',
		'No. of Defects': 'No. of Found Work',
		'Pending Red Pen(s)': 'Pending Green Pen(s)',
		'Plant Unit': 'Equipment',
		'Provide Feedback': 'Add Green Pen',
		'.modal-titleRed Pen(s)': 'Green Pen(s)',
		'.card-titleWork Order Feedback': 'Work Order Green Pen List',
		Name: 'Description'
	},
	userGroups: ['Admin', 'Standard user', 'App user']
};
